Add missing alt property to image tags
hashlab/hash-landingpage pull request #14
Opened 2020-07-19 05:23 UTC by otaviopace

The `img` tags were missing the `alt` property which are important to blind people I guess, so I've added them.

However I don't know if they should be in portuguese or english, since the page has both languages. I've added in english since the whole code and properties are in english, but if you feel it should be in portuguese I can translate them 😉

2020-07-19 06:02 UTC, otaviopace commented
Okay, I just realised that there are two `index.html` one for each language 😅 
I guess I will move the work done here to `en/index.html` and create similar `alt` properties in portuguese for the original `index.html`.

2020-07-19 16:34 UTC, otaviopace commented
Fixed, both portuguese and english versions have `alt` attribute on images 🎉

2020-07-20 20:30 UTC, MarcoWorms commented
Hey @otaviopace thanks a lot for the contribution!

Since the use of the alt tag is supposed to help blind people it would be nice if they have a human-like readability, so instead of using "lisp-case" we should have the alt text in "Normal Case" (idk how is this case type is formally called haha)

Thanks @heyvito that have pointed out to the alt standard: https://www.w3.org/TR/WCAG20-TECHS/H37.html

I can make the commit that changes what you have done to use Normal Case, just let me know if i can take over the PR or if you want to do it by yourself ;)

2020-07-20 20:35 UTC, MarcoWorms requested changes
change requested: replace casing for all instances of alt-text

example of how it is as of now:
`alt="hash-menu-logo"`

example of how it is expected to be:
`alt="Hash Menu Logo"`

2020-07-20 20:43 UTC, otaviopace commented
Okay, I will change then 🙂

2020-07-20 20:43 UTC, heyvito commented
> Since the use of the alt tag is supposed to help blind people it would be nice if they have a human-like readability, so instead of using "lisp-case" we should have the alt text in "Normal Case" (idk how is this case type is formally called haha)

@MarcoWorms Just for curiosity's sake, it is called "Sentence case". Nothing special, and actually quite infuriating it doesn't have a better name. There you go. Now you know how it is formally called. 😛

2020-07-21 18:05 UTC, otaviopace commented
"Sentence case" also know as phrase 😂 
So I've fixed the issues, you can review if the `alt` text is good.
Thanks for the knowledge btw 🙂

2025-06-18 18:28 UTC, closed without merging